# example profiles.yml file
jaffle_shop:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: 'ODBC Driver 18 for SQL Server' # (The ODBC Driver installed on your system)
      server: 192.168.2.118
      port: 1433
      database: DataTeam_test
      schema: dbo
      user: paul.huang
      password:
      encrypt: false
